(deftheme zeeter
  "Created 2022-05-20.")

(custom-theme-set-faces
 'zeeter
 '(default ((t (:family "Cousine" :foundry "GOOG" :width normal :height 105 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#b0bcce" :background "#1f2226" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#C3D0DF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#83CB55"))))
 '(highlight ((t (:foreground "#1f2226" :background "#86dc2f"))))
 '(region ((t (:extend t :foreground "#A28BE7" :background "#272c3b"))))
 '(shadow ((t (:foreground "#717ea5"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "#606873"))))
 '(font-lock-builtin-face ((t (:foreground "#877CEB"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#606873"))))
 '(font-lock-constant-face ((t (:foreground "#4F9FD2"))))
 '(font-lock-doc-face ((t (:foreground "#6e788c"))))
 '(font-lock-function-name-face ((t (:foreground "#c291eb"))))
 '(font-lock-keyword-face ((t (:foreground "#83CB55"))))
 '(font-lock-negation-char-face ((t (:foreground "#4F9FD2"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#67bfba" :background "#26303d"))))
 '(font-lock-type-face ((t (:foreground "#877CEB"))))
 '(font-lock-variable-name-face ((t (:foreground "#C264C6"))))
 '(font-lock-warning-face ((t (:foreground "#d06985"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#4F9FD2"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#AD83EB" :background "#1f2226"))))
 '(header-line ((t (:foreground "#83CB55" :background "#343a4f"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width 1 :color "#3c4666" :style nil) :foreground "#b0bcce" :background "#2b2f37"))))
 '(mode-line-buffer-id ((t (:weight normal :foreground "#b9b174"))))
 '(mode-line-emphasis ((t (:weight normal :foreground "#b0bcce"))))
 '(mode-line-highlight ((t (:weight bold :foreground "#83CB55"))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#3c4666" :style nil) :foreground "#606873" :background "#1f2226"))))
 '(isearch ((t (:weight bold :foreground "#d06985" :background "#3e4044"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:inherit (highlight)))))
 '(match ((t (:foreground "#b95e76" :background "#1f2024"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'zeeter)
